/* Main.c file generated by New Project wizard
 *
 * Created:   ?? 1? 19 2026
 * Processor: 80C31
 * Compiler:  Keil for 8051
 */

#include "reg52.h"
typedef unsigned char u8;
typedef unsigned int u16;

# define SMG_A_DP_PORT P0
u8 gsmg_code[] = {
	0x3f, 0x06, 0x5b, 0x4f, 0x66, 0x6d, 0x7d, 0x07, 
	0x7f, 0x6f, 0x77, 0x7c, 0x39, 0x5e, 0x79, 0x71
};  // common negative SSD.

void delay_10us(u16 ten_us)
{
	while(ten_us--);
}

void main(void)
{ 
	int i;
	while (1)
	{	SMG_A_DP_PORT = 0xff;
		delay_10us(65535);
		for(i = 0; i < 10; i++)
		{
			SMG_A_DP_PORT = gsmg_code[i];
			delay_10us(65535);
		}
	}
}

