/* Main.c file generated by New Project wizard
 *
 * Created:   ÷‹“ª 1‘¬ 19 2026
 * Processor: 80C31
 * Compiler:  Keil for 8051
 */

#include <reg52.h>
#include <intrins.h>

void delay(void)
{
   unsigned char i, j;
   for(i = 1; i<=200; i++)
      for(j = 1; j <= 125; j++);
}

void main(void)
 {
   unsigned char i;
   P2 = 0xfe;
   delay(); 
   
   while (1)
   {
      for(i = 1; i <= 7; i++)
      {
	 P2 = _crol_(P2, 1);
	 delay();
      }
      for(i = 1; i <= 7; i++)
      {
	 P2 = _cror_(P2, 1);
	 delay();
      }
   }
 }