/* Main.c file generated by New Project wizard
 *
 * Created:   ?? 1? 19 2026
 * Processor: 80C31
 * Compiler:  Keil for 8051
 */

#include "reg52.h"
#define SMG_PORT P0

typedef unsigned char u8;
typedef unsigned int u16;

sbit LED1 = P2^0;
sbit LED2 = P2^1;

void delay_us(unsigned int us)
{
    while(us--);
}

int0_srv() interrupt 0 
{
	delay_us(10000);
	LED1 = ~LED1;
}

int1_srv() interrupt 2
{
	delay_us(10000);
	LED2 = ~LED2;
}


void main(void)
{
	IT0 = 1;
	IT1 = 1;
	IE = 0X85;
	while (1)
	{	
		
		
	}
}

