/* Main.c file generated by New Project wizard
 *
 * Created:   ?? 1? 19 2026
 * Processor: 80C31
 * Compiler:  Keil for 8051
 */

#include "reg52.h"

#define SMG_PORT P0
#define KEY_MATRIX_PORT P1

typedef unsigned char u8;
typedef unsigned int u16;

sbit LSA = P2^2;
sbit LSB = P2^3;
sbit LSC = P2^4;



u8 gsmg_code[] = {
	0x3f, 0x06, 0x5b, 0x4f, 0x66, 0x6d, 0x7d, 0x07, 
	0x7f, 0x6f, 0x77, 0x7c, 0x39, 0x5e, 0x79, 0x71
};  // common negative SSD. 0~9, A~F

void delay_10us(u16 ten_us)
{
	while(ten_us--);
}

u8 key_matrix_ranks_scan(void)  // matrix rank scan method
{
	u8 key_value = 0; // the key which is pressed.
	KEY_MATRIX_PORT = 0xf7;  // set the first column line to 0.
	if(KEY_MATRIX_PORT != 0xf7)
	{
		delay_10us(1000);
		switch(KEY_MATRIX_PORT)
		{
			case 0x77: key_value = 1; break;
			case 0xb7: key_value = 5; break;
			case 0xd7: key_value = 9; break;
			case 0xe7: key_value = 13; break;
		}
	}
	KEY_MATRIX_PORT = 0xfb;  // set the second column line to 0.
	if(KEY_MATRIX_PORT != 0xfb)
	{
		delay_10us(1000);
		switch(KEY_MATRIX_PORT)
		{
			case 0x7b: key_value = 2; break;
			case 0xbb: key_value = 6; break;
			case 0xdb: key_value = 10; break;
			case 0xeb: key_value = 14; break;
		}
	}
	KEY_MATRIX_PORT = 0xfd;  // set the third column line to 0.
	if(KEY_MATRIX_PORT != 0xfd)
	{
		delay_10us(1000);
		switch(KEY_MATRIX_PORT)
		{
			case 0x7d: key_value = 3; break;
			case 0xbd: key_value = 7; break;
			case 0xdd: key_value = 11; break;
			case 0xed: key_value = 15; break;
		}
	}
	KEY_MATRIX_PORT = 0xfe;  // set the forth column line to 0.
	if(KEY_MATRIX_PORT != 0xfe)
	{
		delay_10us(1000);
		switch(KEY_MATRIX_PORT)
		{
			case 0x7e: key_value = 4; break;
			case 0xbe: key_value = 8; break;
			case 0xde: key_value = 12; break;
			case 0xee: key_value = 16; break;
		}
	}
	return key_value;
}

u8 key_matrix_flip_scan(void)  // flip scan method
{
	
}

void main(void)
{ 
	while (1)
	{	
		u8 key_value = 0;
		LSC = 0; LSB = 0; LSA = 0;
		key_value = key_matrix_ranks_scan();
		if(key_value != 0) // this if satement is very important.
			SMG_PORT = gsmg_code[key_value-1];
	}
}

