/* Main.c file generated by New Project wizard
 *
 * Created:   ?? 1? 19 2026
 * Processor: 80C31
 * Compiler:  Keil for 8051
 */

#include "reg52.h"
typedef unsigned char u8;

u8 set_bit_to_zero(u8 num, u8 i)  // set the i-th bit of num to 0, where i should be in the range [0, 7].
{
		if(i < 8)
			num &= ~(1 << i);
		return num;
}
	

u8 swap_two_bits(u8 num, u8 i, u8 j) 
	// swap the i-th and j-th bits of num. i and j should be in the range [0, 7], and i != j.
{
		
		u8 bit_0, bit_1;
		if(i >= 8 || j >= 8 || i == j)
        return num;
		
		// extract these two digits
		bit_0 = (num >> i) & 0x01;
		bit_1 = (num >> j) & 0x01;
		
		// erase these two digits in num, i.e., set them to 0
		num = set_bit_to_zero(num, i);
		num = set_bit_to_zero(num, j);
	
		num |= bit_0 << j;
		num |= bit_1 << i;
		return num;
}

void main(void)
 { 

	 char key = 0;
	 P0 = 0x00;
	 P2 = 0xff; // turn off all LEDs.
   while (1)
   {
			key = P3 & 0x0f;
			if (key != 0x0f)
			{
				key |= 0xf0; // set the upper 4 bits of key to all 1's.
				key = swap_two_bits(key, 0, 1); // swap the 0-th and 1-the bits of key
				P2 = key;
			}
   }
 }

