/* Main.c file generated by New Project wizard
 *
 * Created:   ?? 1? 19 2026
 * Processor: 80C31
 * Compiler:  Keil for 8051
 */

#include "reg52.h"
#define SMG_PORT P0
typedef unsigned char u8;
typedef unsigned int u16;

sbit LSA = P2^2;
sbit LSB = P2^3;
sbit LSC = P2^4;



u8 gsmg_code[] = {
	0x3f, 0x06, 0x5b, 0x4f, 0x66, 0x6d, 0x7d, 0x07, 
	0x7f, 0x6f, 0x77, 0x7c, 0x39, 0x5e, 0x79, 0x71
};  // common negative SSD. 0~9, A~F

void delay_10us(u16 ten_us)
{
	while(ten_us--);
}

void smg_display(void)
{
	u8 i = 0;
	for(i = 0; i < 8; i++)
	{
		switch(i)
		{
			case 0: LSC = 1; LSB = 1; LSA = 1; break;
			case 1: LSC = 1; LSB = 1; LSA = 0; break;
			case 2: LSC = 1; LSB = 0; LSA = 1; break;
			case 3: LSC = 1; LSB = 0; LSA = 0; break;
			case 4: LSC = 0; LSB = 1; LSA = 1; break;
			case 5: LSC = 0; LSB = 1; LSA = 0; break;
			case 6: LSC = 0; LSB = 0; LSA = 1; break;
			case 7: LSC = 0; LSB = 0; LSA = 0; break;
		}
		SMG_PORT = gsmg_code[i];
		delay_10us(100);
		SMG_PORT = 0x00;
	}
}

void main(void)
{ 
	while (1)
	{	
		smg_display();
	}
}

